language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '8'
  - '10'
matrix:
  include:
    - node_js: 10
      script: npm run lint
script:
  - node --throw-deprecation ./node_modules/.bin/tape test/*.js
